name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "mydocker.v6.navy"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.mydocker.v6.navy", custom_domain = true },
   { pattern = "quay.mydocker.v6.navy", custom_domain = true },
   { pattern = "gcr.mydocker.v6.navy", custom_domain = true },
   { pattern = "k8s-gcr.mydocker.v6.navy", custom_domain = true },
   { pattern = "k8s.mydocker.v6.navy", custom_domain = true },
   { pattern = "ghcr.mydocker.v6.navy", custom_domain = true },
   { pattern = "cloudsmith.mydocker.v6.navy", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.mydocker.v6.navy", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
